name: 'BunnyCDN storage deployer'
description: 'BunnyCDN storage deployer'
inputs:
  source:
    description: 'target directory to be deployed'
    required: true
    default: './dist'
  storageZoneName:
    required: true
  accessKey:
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'upload-cloud'
  color: 'orange'
