name: "BunnyAction"
description: "BunnyCDN GitHub Action for deploying files to Bunny Storage"
inputs:
  source:
    description: "target directory to be deployed"
    required: false
    default: "./dist"
  storageZoneName:
    description: "storage zone name"
    required: false
  accessKey:
    description: "Storage zone access key"
    required: false
  zoneId:
    description: "Storage zone id"
    required: false
  zoneKey:
    description: "Storage zone key"
    required: false
  dangerouslyDeleteAllExistingData:
    description: "If set to true will delete all files before uploading new files"
    required: false
runs:
  using: "node12"
  main: "dist/index.js"
branding:
  icon: "upload-cloud"
  color: "orange"
