name: 'BunnyCDN GH Action'
description: 'BunnyCDN GH Action'
inputs:
  source:
    description: 'target directory to be deployed'
    required: true
    default: './dist'
  storageZoneName:
    description: 'storage zone name'
    required: true
  accessKey:
    description: 'Storage zone access key'
    required: true
  zoneId:
    description: 'Storage zone id'
    required: false
  zoneKey:
    description: 'Storage zone key'
    required: false
    default: ''
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: 'upload-cloud'
  color: 'orange'
